# Generated by Django 3.1.5 on 2021-01-26 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 1, 26, 7, 45, 8, 126063, tzinfo=utc))),
                ('author', models.TextField()),
            ],
        ),
    ]
