# Generated by Django 3.1.5 on 2021-01-26 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 7, 46, 24, 603513, tzinfo=utc)),
        ),
    ]
